#!/bin/bash
# Run from geometricVofExt top-level directory only
cd "${0%/*}" || exit
wmake -check-dir "$WM_PROJECT_USER_DIR/modules/geometricVofExt" 2>/dev/null || {
    echo "Error (${0##*/}) : not located in \$WM_PROJECT_USER_DIR/modules/geometricVofExt"
    echo "    Check your OpenFOAM environment and installation"
    exit 1
}
#------------------------------------------------------------------------------

echo
echo "*********** Compile CGAL with GMP and MPFR Using Intel Compiler ************"
echo

# change to intel compilers
export WM_COMPILER=Icx
source $WM_PROJECT_DIR/etc/bashrc

# Modify $WM_PROJECT_DIR/etc/config.sh/compiler
[ -f $WM_PROJECT_DIR/etc/config.sh/compiler_backup ] || cp $WM_PROJECT_DIR/etc/config.sh/compiler $WM_PROJECT_DIR/etc/config.sh/compiler_backup

awk '
    BEGIN {
        in_section = 0
        printed_icx = 0
    }
    /case "\$WM_COMPILER_TYPE" in/ {
        print $0
        in_section = 1
        next
    }
    /system\)/ && in_section && !printed_icx {
        # 先打印原有的 system) 部分
        print
        # 然后添加 Intel 编译器部分
        print ""
        print "# Added for Intel oneAPI compiler support"
        print "Icx)"
        print "    gmp_version=gmp-6.3"
        print "    mpfr_version=mpfr-4.2.2"
        print "    mpc_version=mpc-1.3.1"
        print "    ;;"
        printed_icx = 1
        next
    }
    /^[[:space:]]*;;/ && in_section {
        print $0
        next
    }
    /ThirdParty)/ && in_section {
        print $0
        in_section = 0
        next
    }
    {
        print $0
    }
' $WM_PROJECT_DIR/etc/config.sh/compiler_backup > $WM_PROJECT_DIR/etc/config.sh/compiler


# Modify $WM_PROJECT_DIR/etc/config.sh/settings
[ -f $WM_PROJECT_DIR/etc/config.sh/settings_backup ] || cp $WM_PROJECT_DIR/etc/config.sh/settings $WM_PROJECT_DIR/etc/config.sh/settings_backup

awk '
    BEGIN {
        in_section = 0
        printed_icx = 0
    }
    /case "\$WM_COMPILER_TYPE-\$WM_COMPILER" in/ {
        print $0
        in_section = 1
        next
    }
    /system-Gcc\)/ && in_section && !printed_icx {
        # 先打印原有的 system-Gcc) 部分
        print
        # 然后添加 Intel 编译器部分
        print ""
        print "# Added for Intel oneAPI compiler support"
        print "Icx-Icx)"
        print "    gmpDir=\"\$archDir/\${gmp_version}\""
        print "    mpfrDir=\"\$archDir/\${mpfr_version}\""
        print "    mpcDir=\"\$archDir/\${mpc_version}\""
        print "    _foamAddLibAuto \"\$gmpDir\" && export GMP_ARCH_PATH=\"\$gmpDir\""
        print "    _foamAddLibAuto \"\$mpfrDir\" && export MPFR_ARCH_PATH=\"\$mpfrDir\""
        print "    _foamAddLibAuto \"\$mpcDir\""
        print "    ;;"
        printed_icx = 1
        next
    }
    /^[[:space:]]*;;/ && in_section {
        print $0
        next
    }
    /ThirdParty-Gcc\*\)/ && in_section {
        print $0
        in_section = 0
        next
    }
    {
        print $0
    }
' $WM_PROJECT_DIR/etc/config.sh/settings_backup > $WM_PROJECT_DIR/etc/config.sh/settings


# Renew env of OpenFOAM
source $WM_PROJECT_DIR/etc/bashrc

# change to intel compilers
source ${HOME}/intel/oneapi/setvars.sh --force >/dev/null 2>&1

gmpV=6.3
cp ThirdParty/gmp-${gmpV}.tar.gz $WM_THIRD_PARTY_DIR
mpfrV=4.2.2
cp ThirdParty/mpfr-${mpfrV}.tar.gz $WM_THIRD_PARTY_DIR
mpcV=1.3.1
cp ThirdParty/mpc-${mpcV}.tar.gz $WM_THIRD_PARTY_DIR


cd $WM_THIRD_PARTY_DIR

# Download and unpack GMP, MPFR and MPC
# [ -f gmp-6.2.1.tar.xz ] || wget -nv https://gmplib.org/download/gmp/gmp-6.2.1.tar.xz --no-check-certificate
# [ -d gmp-6.2.1 ] || tar -xf gmp-6.2.1.tar.xz
[ -d gmp-${gmpV} ] || tar -xzf gmp-${gmpV}.tar.gz

# [ -f mpfr-4.1.0.tar.gz ] || wget -nv https://ftp.gnu.org/gnu/mpfr/mpfr-4.1.0.tar.gz --no-check-certificate
# [ -d mpfr-4.1.0 ] || tar -xzf mpfr-4.1.0.tar.gz
[ -d mpfr-${mpfrV} ] || tar -xzf mpfr-${mpfrV}.tar.gz

# [ -f mpc-1.2.1.tar.gz ] || wget -nv https://ftp.gnu.org/gnu/mpc/mpc-1.2.1.tar.gz --no-check-certificate
# [ -d mpc-1.2.1 ] || tar -xzf mpc-1.2.1.tar.gz
[ -d mpc-${mpcV} ] || tar -xzf mpc-${mpcV}.tar.gz


# Remove old build
echo "Cleaning old builds for Intel compiler..."
rm -rf ./build/$WM_ARCH$WM_COMPILER/gmp-${gmpV}
rm -rf ./build/$WM_ARCH$WM_COMPILER/mpc-${mpcV}
rm -rf ./build/$WM_ARCH$WM_COMPILER/mpfr-${mpfrV}

rm -rf ./platforms/$WM_ARCH$WM_COMPILER/gmp-${gmpV}
rm -rf ./platforms/$WM_ARCH$WM_COMPILER/mpc-${mpcV}
rm -rf ./platforms/$WM_ARCH$WM_COMPILER/mpfr-${mpfrV}

rm -rf ./build/$WM_ARCH$WM_COMPILER/CGAL-*

rm -rf ./platforms/$WM_ARCH$WM_COMPILER/boost_*
rm -rf ./platforms/$WM_ARCH$WM_COMPILER/CGAL-*


# Build with Intel compiler strategy
echo "Building dependencies with system GCC first..."
# compile packages with GCC compiler first
export WM_COMPILER=Gcc
source $WM_PROJECT_DIR/etc/bashrc

./makeGcc gcc-system gmp-${gmpV} mpfr-${mpfrV} mpc-${mpcV}

echo "Building CGAL with Intel compiler..."
# change to intel compilers
export WM_COMPILER=Icx
source $WM_PROJECT_DIR/etc/bashrc
source ${HOME}/intel/oneapi/setvars.sh --force >/dev/null 2>&1

# compile CGAL. In building src/CGALVof, patches/iterator.h should be copied to 
# ${WM_THIRD_PARTY_DIR}/platforms/linux64Icx/CGAL-4.14.3/include/CGAL/boost/graph/
./makeCGAL -with-lib gmp-${gmpV} mpfr-${mpfrV}

echo
echo "********************************* Done *********************************"
echo

#------------------------------------------------------------------------------