#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication renumberMesh -overwrite

ln -rsf ../exactSolutions/0/alpha.water.exact 0/alpha.water

runApplication plicVofAdvectionFoam

./Allrun.linkExactSolutions

runApplication calcVofAdvectionErrors

writeVtkSeries plicInterface plicSurf
writeVtkSeries isoInterface isoSurf

touch ${PWD##*/}.foam

#------------------------------------------------------------------------------
