#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allrun.pre

runApplication decomposePar -cellDist -fileHandler collated

runParallel  $(getApplication) -fileHandler collated

writeVtkSeries isoInterface isoSurf
writeVtkSeries hole face1
writeVtkSeries zPlaneCut face1

touch ${PWD##*/}.foam

#------------------------------------------------------------------------------
