#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication setVofField -np 8

runApplication setShapedFields -np 8

runApplication decomposePar -fileHandler collated

runParallel $(getApplication) -fileHandler collated

writeVtkSeries plicInterface plicSurf
writeVtkSeries isoInterface isoSurf

touch ${PWD##*/}.foam

#------------------------------------------------------------------------------
