#!/bin/sh
cd "${0%/*}" || exit    # Run from this directory
#------------------------------------------------------------------------------

wclean libso dynamicRefine2DFvMesh

unlink $WM_PROJECT_USER_DIR/modules/geometricVofExt/src/SimPLIC/reconstruction/reconstructedDistanceFunction.H

unlink $WM_PROJECT_USER_DIR/modules/geometricVofExt/src/SimPLIC/reconstruction/reconstructedDistanceFunction.C

wclean libso SimPLIC

wclean libso CGALVof

#------------------------------------------------------------------------------
