#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication decomposePar -fileHandler collated

runParallel  $(getApplication) -fileHandler collated

writeVtkSeries isoInterface isoSurf
writeVtkSeries floatingObject floatingObject
writeVtkSeries stationaryWalls stationaryWalls

touch ${PWD##*/}.foam

#------------------------------------------------------------------------------
